### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by nasvamees** [2Luciferuwu2/FiveM-LuaInjector#2]
Hello i downloaded all of the files to my desktop, when i klick the injector an discord opens up, automaticly logging me out of my account so only screen i see is "LOGIN" screen. And the hack doesnt open up

**Comment by 2Luciferuwu2** [comment]
It worked for me are you sure u didn't download some kinda virus?

**Comment by nasvamees** [comment]
in the folder there is "lua-injector.exe" right ?

**Comment by 2Luciferuwu2** [comment]
Yup

**Comment by nasvamees** [comment]
whats your discord

**Comment by nasvamees** [comment]
could i show you for a sec

**Comment by 2Luciferuwu2** [comment]
I'll see what's happening when i get home
